name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: front/package-lock.json
    - run: npm ci
      working-directory: front/
    - run: npm run build
      working-directory: front/
    - uses: actions/upload-artifact@v2
      with:
        name: frontend
        path: front/dist-prod/
        if-no-files-found: error
        retention-days: 1
  build:
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: frontend
        path: front/
    - uses: actions-rs/toolchain@v1
    - uses: Swatinem/rust-cache@v1
    - name: Build
      run: cargo build --release
    - uses: actions/upload-artifact@v2
      with:
        name: mdj
        path: target/release/mdj
        if-no-files-found: error
